#
# Configuration file for tracking using sliding
# 

TO:
    contactMode: 'sticking'  # 'sticking', 'sliding_cc', or 'sliding_mi'
    # contactMode: 'sliding_cc_slack'  # 'sticking', 'sliding_cc', or 'sliding_mi'
    solverName: 'gurobi'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
    W_x: [1.0, 1.0, 0.01, 0.]  # diagonal state weights
    W_u: [0.1, 0.1, 0., 0.]  # diagonal control weights
    K_goal: 100
    X_goal: null
    linDynFlag: False
    codeGenFlag: False
    noPrintingFlag: True
    phases: null
