#
# Configuration file for tracking using sliding
# 

dynamics:
    # xLenght: 0.091 #  [meter]
    # yLenght: 0.144 #  [meter]
    xLenght: 0.08 #  [meter]
    yLenght: 0.15 #  [meter]
    pusherRadious: 0.009 #  [meter]
    pusherFricCoef: 0.3
    pusherForceLim:  0.3
    pusherAngleVelLim: 3.0
    Kz_max: 50
    Kz_min: 0.1
    xFacePsiLimit: 0.9
    # yFacePsiLimit: 0.405088
    yFacePsiLimit: 0.52

TO:
    contactMode: 'sliding_cc_slack'  # 'sticking', 'sliding_cc', 'sliding_cc_slack', or 'sliding_mi'
    # contactMode: 'sliding_mi'  # 'sticking', 'sliding_cc', 'sliding_cc_slack', or 'sliding_mi'
    solverName: 'ipopt'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
    # solverName: 'gurobi'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
    W_x: [50.0, 50.0, 0.1, 0.]  # diagonal state weights
    W_u: [0.01, 0.01, 0., 0.]  # diagonal control weights
    # W_u: [0.0, 0.0, 0.0, 0.]  # diagonal control weights
    K_goal: 10
    X_goal: null
    # X_goal: [0.3, 0.4, 0., 0.]
    linDynFlag: False
    #linDynFlag: True
    codeGenFlag: False
    noPrintingFlag: True
    phases: null
    numObs: 0
    # phases: [1, 5, 5, 5, 3]
